[Refactor] Auth 기능 구조 변경
boostcampwm-2024/web06-harmony pull request #110
Opened 2024-11-20 13:28 UTC by jjeonghak

[//]: # (PR 제목은 [Feat] {제목} 형식으로 작성해주세요.)
[//]: # (Reviewer, Assignees, Labe을 붙여주세요.)

## 관련 이슈 번호

[//]: # (해당 PR이 어떤 이슈와 관련이 있는지 작성해주세요.)
[//]: # (ex. close #1, resolve #2)

close #108 

## 작업 내용

[//]: # (해당 PR에서 어떤 작업을 했는지 작성해주세요.)

* auth 기능 구조 변경
* 토큰 전달 방식 수정

2024-11-20 13:59 UTC, yangchef1 approved these changes

2024-11-24 12:49 UTC, PMtHk requested changes

2024-11-24 12:49 UTC, PMtHk commented on apps/server/src/account/auth.controller.ts
> +  @UseGuards(RefreshTokenGuard)
🔴 
너무 늦어서 죄송합니다.
여기 AccessToken 을 통해 검증하는 게 자연스러운 것 같아요.

아마, 만료되었을 때에도 로그아웃을 할 수 있도록 고려하신 것 같은데,
401 이 발생하면, refresh 를 한 후 다시  로그아웃을 하는 것이 자연스러운 방향이 아닐까 싶어요!

2024-11-24 12:49 UTC, PMtHk commented on apps/server/src/account/strategy/refreshToken.strategy.ts
> +      jwtFromRequest: ExtractJwt.fromExtractors([(req) => req.cookies.refreshToken]),
👍🏻

2024-11-24 12:51 UTC, jjeonghak commented on apps/server/src/account/auth.controller.ts
> +  @UseGuards(RefreshTokenGuard)
충돌난거 병합하면서 수정해두겠습니다~

2024-11-25 14:07 UTC, PMtHk approved these changes

2024-11-25 14:08 UTC, merged