[Feat] 칸반 보드 뷰 생성
boostcampwm-2024/web06-harmony pull request #34
Opened 2024-11-06 15:26 UTC by iam454

## 관련 이슈 번호

#4 

## 작업 내용

- Card 컴포넌트 생성
- Section 컴포넌트 생성
- 두 컴포넌트를 활용하여 칸반 보드 뷰 구현

## 설명

쓰이지 않을 것 같지만 남겨둔 컴포넌트가 몇 개 있는데요.
스크린샷 부분에서 생각을 나열해보겠습니다. ㅎ.ㅎ

### Card 컴포넌트

shadcn의 card 컴포넌트입니다.
padding, font-weight, font-size 등 default 와는 살짝 다른 스타일 사항이 있습니다.

### Section 컴포넌트

Section 컴포넌트를 따로 만들까했지만, shadcn의 card 컴포넌트의 구조가 매력적이었습니다.
그래서 그대로 갖고와 이름만 section 컴포넌트로 바꾸었습니다. 😅
이것 역시 padding 등 default 와는 살짝 다른 스타일 사항이 있습니다.

## 스크린샷

<img width="1025" alt="Screenshot 2024-11-06 at 11 36 53 PM" src="https://github.com/user-attachments/assets/e8a5db02-8b5d-47d8-b1bb-ff7419a4e46d">

깃허브 프로젝트를 좀 따라해봤는데, 어떤가요?

CardDescription도 필요할까요?

CardContent를 활용해서 라벨을 보여주고,
(하위 태스크를 보여줄 것이라면) CardFooter를 활용하면 좋지 않을까? 생각 중입니다.

SectionDescription도 필요할까요?

SectionFooter를 활용하여 새 카드 만들기 버튼을 두면 되겠다! 싶었습니다.

## 논의하면 좋을 사항

### 자료구조

데이터의 형태를 상상해보았습니다.
주엽님이 생각 중이신 형태도 있었을까요?

```js
const initialColumns = [
  {
    id: '0',
    title: '할 일',
    tasks: [
      { id: '1', title: '프로젝트 계획 수립' },
      { id: '2', title: '디자인 초안 작성' },
    ],
  },
  {
    id: '1',
    title: '진행 중',
    tasks: [
      { id: '3', title: '프로젝트 계획 수립' },
    ],
  },
];
```

이것저것 넣어보면 이런 형태가 될 수도 있을 것 같습니다.

```js
{
  id: '0',
  title: '할 일',
  description: '아직 시작되지 않은 일입니다',
  tasks: [
    { id: '1', title: '프로젝트 계획 수립' },
    { id: '2', title: '디자인 초안 작성' },
    {
      id: '6',
      title: '디자인 초안 작성',
      labels: [
        { id: '1', title: 'sprint 1' },
        { id: '4', title: 'story 1' },
      ],
    },
  ],
},
```

2024-11-06 15:48 UTC, PMtHk commented
완석님 수고하셨습니다!

이건 리뷰사항은 아니라 따로 코멘트로 남겨봅니다.
혹시 repository 를 fork 하시고 작업을 하신건가요?

브랜치를 확인하려고 보니 다음과 같이 나타나서 여쭤봅니다~

<img width="600" alt="스크린샷 2024-11-07 오전 12 47 45" src="https://github.com/user-attachments/assets/dd425b36-dc47-468f-88a7-6a3c6b525640">

2024-11-06 16:10 UTC, PMtHk requested changes
> SectionDescription도 필요할까요?

저는 컬럼 하위에 몇 개의 태스크가 있는지, 총 작업 예상 시간은 어느정도인지를 표시해주면 좋을 것 같다고 생각합니다.
(아래 사진의 빨간 밑줄 부분입니다.)
<img width="290" alt="스크린샷 2024-11-07 오전 1 07 12" src="https://github.com/user-attachments/assets/44db5bc0-e982-4189-b991-3a0fb0ae7b68">

> 데이터의 형태를 상상해보았습니다.
> 주엽님이 생각 중이신 형태도 있었을까요?

완석님의 코드와 제가 일반적으로 사용했던 스타일이 유사합니다.
지금 적용되어 있는 형태로 상태를 관리해도 좋을 것 같습니다.

2024-11-06 16:10 UTC, PMtHk commented on apps/client/src/App.tsx
> +				<Button>default</Button>
이 부분은 과거의 제가 shadcn/ui 적용을 확인 시켜드리기 위해 작성해 둔 부분입니다.
보드 뷰가 생긴 상태에서는 제거해주셔도 좋을 것 같습니다.

2024-11-06 16:10 UTC, PMtHk commented on apps/client/src/App.tsx
> +const initialColumns = [
제가 처음 생각한 컬럼별 태스크의 구조와 일치합니다!

2024-11-06 16:10 UTC, PMtHk commented on apps/client/src/App.tsx
> +									<Card key={task.id} className="bg-[#ffffff]">
Task 를 Card 컴포넌트를 사용해 관리하고 있습니다.
별도로 TaskCard 라는 컴포넌트를 만들어서 사용한다면, 코드의 길이를 줄일 수 있을 것 같습니다.
Column 도 마찬가지구요!

ex) TaskCard 컴포넌트를 만들어서 <Card> ... </Card> 부분 분리

2024-11-07 06:30 UTC, jjeonghak approved these changes

2024-11-07 06:33 UTC, PMtHk approved these changes
수고하셨습니다.

2024-11-07 06:33 UTC, merged