[Feat] 태스크 생성 API를 구현
boostcampwm-2024/web06-harmony pull request #39
Opened 2024-11-09 11:38 UTC by yangchef1

[//]: # (PR 제목은 [Feat] {제목} 형식으로 작성해주세요.)
[//]: # (Reviewer, Assignees, Labe을 붙여주세요.)

## 관련 이슈 번호

[//]: # (해당 PR이 어떤 이슈와 관련이 있는지 작성해주세요.)
[//]: # (ex. close #1, resolve #2)
close #8 

## 작업 내용

[//]: # (해당 PR에서 어떤 작업을 했는지 작성해주세요.)

- [x] Task, Section 엔티티 클래스 작성
- [x] Task 생성 DTO 작성 
- [x] Task 생성 API 구현 

## 고민과 학습내용

[//]: # (해당 작업을 하면서 고민했던 점이나 학습한 내용을 작성해주세요.)
[//]: # (팀 노션의 학습로그와 연결해도 좋습니다.)

## 스크린샷

[//]: # (가능한 경우 스크린샷을 첨부해주세요.)

2024-11-09 12:02 UTC, PMtHk requested changes
🔴 prettier 설정에 아래와 같이 설정해두어서, indent 가 두 글자여야 하는데,
조금 문제가 있는 것 같습니다. IDE  설정이 되어 있는지 한번만 확인 부탁드립니다.
```
  "useTabs": true,
  "tabWidth": 2,
```

2024-11-09 12:02 UTC, PMtHk commented on apps/server/src/task/domain/task.entity.ts
> +import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
🟢  
domain 내부에 entity 가 설정되어 있어서, 조금 어색하게 느껴집니다.
저는 엔티티를 조합해 만든 도메인 객체를 생각하고 들어왔는데, 엔티티가 보여서 그런 것 같아요.

2024-11-09 12:36 UTC, yangchef1 commented on apps/server/src/task/domain/task.entity.ts
> +import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
entity 뿐 아니라 해당 도메인에서 사용할 enum 등을 모아두는 디렉토리라고 생각하고 `domain`으로 설정했는데, entitiy는 `entity` 디렉토리에 모아두는게 더 직관적일 수 있을 것 같네요 ...!

2024-11-10 06:45 UTC, PMtHk commented on apps/server/src/task/domain/task.entity.ts
> +import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
그렇군요! 도메인에서 사용할 부분을 모아두는 것은 좋은 것 같아요!
만약 그렇게 된다면 나중에 같은 기능을 위한 controller, service, modulde 도 묶어도 좋겠군요!

2024-11-10 06:46 UTC, PMtHk submitted a review, later dismissed

2024-11-10 07:09 UTC, jjeonghak submitted a review, later dismissed

2024-11-10 07:34 UTC, iam454 submitted a review, later dismissed
희철님~ resolve conflict 부탁드립니당

2024-11-11 04:04 UTC, PMtHk approved these changes

2024-11-11 04:59 UTC, jjeonghak approved these changes

2024-11-11 05:03 UTC, merged